server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        deregister: true
        service-name: ${spring.application.name}
        # 这个服务需要主动开启心跳机制——why?
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
#          filters:
#            - SimpleAuthGlobalFilter
        - id: feign-service
          uri: lb://feign-service
          predicates:
            - Path=/api/feign/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**