server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        deregister: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
#          filters:
#            - SimpleAuthGlobalFilter
        - id: feign-service
          uri: lb://feign-service
          predicates:
            - Path=/api/feign/**