server:
  port: 8002
  servlet:
    context-path: /api/feign
spring:
  application:
    name: feign-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        deregister: true
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health